name: AWS Lambda Deploy 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v4.1.4
      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: lambda update
        run: |
          zip -r package.zip ./
          aws lambda update-function-code --function-name websites-render --zip-file fileb://package.zip --publish
